#
# Source:
#   - https://github.com/CircleCI-Public/circleci-demo-python-flask/blob/master/.circleci/config.yml
#   - https://github.com/CircleCI-Public/circleci-demo-python-django/blob/master/.circleci/config.yml
#
# Author: rodolfo.lotte
# Organization: Bioverse Labs
#

version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  linux-prepare-dependencies:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Download GDAL dependencies
          command: |
            sudo apt -y update
            sudo apt -y upgrade
            sudo apt -y install libxml2-dev libxslt1-dev zlib1g-dev g++ gcc
            sudo apt -y install gdal-bin libgdal-dev
      - run:
          name: Creating virtual environment
          command: |
            python3 -m venv .venv
      - run:
          name: Install project's requirements
          command: |
            . .venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
      - save_cache:
          key: deps2-{{ checksum "requirements.txt" }}
          paths:
            - '.venv'
      - run:
          name: Install pip GDAL requirement
          command: |
            . .venv/bin/activate
            pip install GDAL==$(gdal-config --version | awk -F'[.]' '{print $1"."$2}')
  linux-build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
  linux-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: echo "Initiating test job"
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - linux-prepare-dependencies
#      - linux-build
#      - linux-test:
#          requires:
#            - linux-build
#      - macos-prepare-dependencies
#      - macos-build
#      - macos-test:
#          requires:
#            - macos-build
#      - windows-prepare-dependencies
#      - windows-build
#      - windows-test:
#          requires:
#            - windows-build
